### ISSUE TITLE
RuntimeError: exception:  vector::_M_range_check: __n Error

### ISSUE THREAD

**Issue by dxy257** [precimed/mixer#95]
Could someone please help me with this? I am not sure what caused this error?

Singularity> python3 /home/dxy257/mixer/precimed/mixer.py fit1       --trait1-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/SSGAC_EDU_2018_no23andMe_noMHC.csv.gz       --out /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/SSGAC_EDU_2018_no23andMe_noMHC.fit.rep1       --extract /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep1.snps       --bim-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.bim       --ld-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.run4.ld       --lib  /home/dxy257/mixer/src/build/lib/libbgmg.so \
>
INFO:root:__init__(lib_name=/tools/mixer/src/build/lib/libbgmg.so, context_id=0)
INFO:root:init_log(/mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/SSGAC_EDU_2018_no23andMe_noMHC.fit.rep1.log)
INFO:root:log_message(***********************************************************************
* mixer.py: Univariate and Bivariate Causal Mixture for GWAS
* Version 1.2.0
* (c) 2016-2020 Oleksandr Frei, Alexey A. Shadrin, Dominic Holland
* Norwegian Centre for Mental Disorders Research / University of Oslo
* Center for Multimodal Imaging and Genetics / UCSD
* GNU General Public License v3
***********************************************************************
Call:
./mixer.py fit1 \
        --out /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/SSGAC_EDU_2018_no23andMe_noMHC.fit.rep1 \
        --lib /home/dxy257/mixer/src/build/lib/libbgmg.so \
        --bim-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.bim \
        --ld-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.run4.ld \
        --trait1-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/SSGAC_EDU_2018_no23andMe_noMHC.csv.gz \
        --extract /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep1.snps
)
INFO:root:__init__(lib_name=/tools/mixer/src/build/lib/libbgmg.so, context_id=0)
Traceback (most recent call last):
  File "/home/dxy257/mixer/precimed/mixer.py", line 23, in <module>
    args.func(args)
  File "/home/dxy257/mixer/precimed/mixer/cli.py", line 646, in execute_fit1_or_test1_parser
    libbgmg = initialize_mixer_plugin(args)
  File "/home/dxy257/mixer/precimed/mixer/cli.py", line 562, in initialize_mixer_plugin
    libbgmg.set_ld_r2_coo_from_file(chr_label, args.ld_file.replace('@', str(chr_label)))
  File "/home/dxy257/mixer/precimed/mixer/libbgmg.py", line 126, in set_ld_r2_coo_from_file
    return self._check_error(self.cdll.bgmg_set_ld_r2_coo_from_file(self._context_id, chr_label, _p2n(filename)))
  File "/home/dxy257/mixer/precimed/mixer/libbgmg.py", line 418, in _check_error
    raise RuntimeError(self.get_last_error())
RuntimeError: exception:  vector::_M_range_check: __n (which is 18446744072511363440) >= this->size() (which is 779354)

**Comment by jiexiong22** [comment]
I had the same problem. Did you solve it？

**Comment by dxy257** [comment]
> Could someone please help me with this? I am not sure what caused this error?
> 
> Singularity> python3 /home/dxy257/mixer/precimed/mixer.py fit1 --trait1-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/SSGAC_EDU_2018_no23andMe_noMHC.csv.gz --out /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/SSGAC_EDU_2018_no23andMe_noMHC.fit.rep1 --extract /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep1.snps --bim-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.bim --ld-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.run4.ld --lib /home/dxy257/mixer/src/build/lib/libbgmg.so \
> 
> > 
> 
> INFO:root:**init**(lib_name=/tools/mixer/src/build/lib/libbgmg.so, context_id=0) INFO:root:init_log(/mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/SSGAC_EDU_2018_no23andMe_noMHC.fit.rep1.log) INFO:root:log_message(***********************************************************************
> 
> * mixer.py: Univariate and Bivariate Causal Mixture for GWAS
> * Version 1.2.0
> * (c) 2016-2020 Oleksandr Frei, Alexey A. Shadrin, Dominic Holland
> * Norwegian Centre for Mental Disorders Research / University of Oslo
> * Center for Multimodal Imaging and Genetics / UCSD
> * GNU General Public License v3
> 
> Call: ./mixer.py fit1 --out /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/SSGAC_EDU_2018_no23andMe_noMHC.fit.rep1 --lib /home/dxy257/mixer/src/build/lib/libbgmg.so --bim-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.bim --ld-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.run4.ld --trait1-file /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/SSGAC_EDU_2018_no23andMe_noMHC.csv.gz --extract /mnt/vstor/SOM_EPBI_XXZ10/dxy257/AD_kidney_function/mixer/sample_GWAS_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep1.snps ) INFO:root:**init**(lib_name=/tools/mixer/src/build/lib/libbgmg.so, context_id=0) Traceback (most recent call last): File "/home/dxy257/mixer/precimed/mixer.py", line 23, in args.func(args) File "/home/dxy257/mixer/precimed/mixer/cli.py", line 646, in execute_fit1_or_test1_parser libbgmg = initialize_mixer_plugin(args) File "/home/dxy257/mixer/precimed/mixer/cli.py", line 562, in initialize_mixer_plugin libbgmg.set_ld_r2_coo_from_file(chr_label, args.ld_file.replace('@', str(chr_label))) File "/home/dxy257/mixer/precimed/mixer/libbgmg.py", line 126, in set_ld_r2_coo_from_file return self._check_error(self.cdll.bgmg_set_ld_r2_coo_from_file(self._context_id, chr_label, _p2n(filename))) File "/home/dxy257/mixer/precimed/mixer/libbgmg.py", line 418, in _check_error raise RuntimeError(self.get_last_error()) RuntimeError: exception: vector::_M_range_check: __n (which is 18446744072511363440) >= this->size() (which is 779354)

**Comment by dxy257** [comment]
Hi there,

I have fixed the issue after modifying my GWAS summary stats file. I also
had a file path error that I fixed on top of that. You may find this post
helpful: https://github.com/precimed/mixer/issues/82

Best,
Diya

**Comment by XuanxiaoLi** [comment]
Hi dxy257,

I am encountering a similar problem with my use of `fit1` in `mixer.py`:

* **Software Version**: 1.2.0
* **Call Command**:
    ```bash
    ./mixer.py fit1 \
        --out /hdd/yinquanting/T2d_heart/hypertension.fit.rep1 \
        --lib /hdd/yinquanting/mixer/src/build/lib/libbgmg.so \
        --bim-file /hdd/yinquanting/mixer/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.bim \
        --ld-file /hdd/yinquanting/mixer/1000G_EUR_Phase3_plink/1000G.EUR.QC.1.run4.ld \
        --trait1-file /hdd/yinquanting/T2d_heart/hypertension.txt.gz \
        --extract /hdd/yinquanting/mixer/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep1.snps
    ```
* **Error Message**:
    ```plaintext
    INFO:root:__init__(lib_name=/hdd/yinquanting/mixer/src/build/lib/libbgmg.so, context_id=0)
    Traceback (most recent call last):
      File "/hdd/yinquanting/mixer/precimed/mixer.py", line 23, in <module>
        args.func(args)
      File "/hdd/yinquanting/mixer/precimed/mixer/cli.py", line 646, in execute_fit1_or_test1_parser
        libbgmg = initialize_mixer_plugin(args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/hdd/yinquanting/mixer/precimed/mixer/cli.py", line 562, in initialize_mixer_plugin
        libbgmg.set_ld_r2_coo_from_file(chr_label, args.ld_file.replace('@', str(chr_label)))
      File "/hdd/yinquanting/mixer/precimed/mixer/libbgmg.py", line 126, in set_ld_r2_coo_from_file
        return self._check_error(self.cdll.bgmg_set_ld_r2_coo_from_file(self._context_id, chr_label, _p2n(filename)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/hdd/yinquanting/mixer/precimed/mixer/libbgmg.py", line 418, in _check_error
        raise RuntimeError(self.get_last_error())
    RuntimeError: exception:  vector::_M_range_check: __n (which is 540606976) >= this->size() (which is 779354)
    ```

I have followed the suggestion in issue #82 and removed NA and 0 SNPs from my GWAS data, but I am still encountering this error. Could you please help me troubleshoot this issue? Is there any additional step or check I should perform to resolve this?

Thank you!

**Comment by chrislaw194** [comment]
@XuanxiaoLi did you ever figure this out? I have the exact same problem
